### ISSUE TITLE
Adding a Drawable

### ISSUE THREAD

**Issue by ghost** [Blitz-Mobile-Apps/react-native-animated-splash#35]
How to add drawable mentioned in this note - https://github.com/Blitz-Mobile-Apps/react-native-animated-splash/blob/master/androidexample.md#important-note ?

**Comment by ethangray909** [comment]
> How to add drawable mentioned in this note - https://github.com/Blitz-Mobile-Apps/react-native-animated-splash/blob/master/androidexample.md#important-note ?

Please refer to [this thread](https://stackoverflow.com/questions/29047902/how-to-add-an-image-to-the-drawable-folder-in-android-studio)
