### ISSUE TITLE
Updating examples and readme

### ISSUE THREAD

**Issue by lapwil** [Blitz-Mobile-Apps/react-native-animated-splash#36]
Hi,

I've seen that you've recently changed the AddImageView to AnimatedImage classes

Can you update your ReadMe and examples ?

I got some issues after updating my packages

```
error: cannot find symbol
import com.blitzapp.animatedsplash.animation.AddImageView;
```

Which was simply due to the new name.

I can make a new PR later this week if you don't have the time to update them

**Comment by ethangray909** [comment]
Hi @lapwil,

Thanks & sorry for the delay. We have made some changes in the code and also all the ReadMe are updated.
