### ISSUE TITLE
Can someone explain me? It's worked yestarday, but not today!

### ISSUE THREAD

**Issue by DenSakhon** [Blitz-Mobile-Apps/react-native-animated-splash#38]
![изображение](https://user-images.githubusercontent.com/108734427/200197261-6d8108f6-00b4-4dd8-98cd-95324b5cd179.png)

 "react": "17.0.2",
"react-native": "0.66.4",
"react-native-animated-splash": "1.3.7",

       buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        androidMapsUtilsVersion = "0.6+"
        ndkVersion = "21.4.7075529"
        kotlinVersion = "1.5.31"

p.s. When im use ./gradlew app:assembleRelease instead of ./gradlew assembleRelease then apk was generated but cannot open the app on device.

**Comment by DenSakhon** [comment]
Solved with: 
``` 
afterEvaluate {
        project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion = 31
                buildToolsVersion = "31.0.0"
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }
            }
        }
    }
```
And in my case set org.gradle.parallel=false to false in gradle.properties

**Comment by 7sameer24** [comment]
I just fixed this issue by replace ./gradlew assembleRelease by ./gradlew app:assembleRelease
