### ISSUE TITLE
RN 0.63.4 pod install

### ISSUE THREAD

**Issue by minayaleon** [Blitz-Mobile-Apps/react-native-animated-splash#5]
i've problem with iOS

Specs satisfying the `RNAnimatedSplash (from `../node_modules/react-native-animated-splash`)` dependency were found, but they required a higher minimum deployment target.

**Comment by minayaleon** [comment]
It' works with minimun ios version: 12

**Comment by ammartariq100** [comment]
go to your podfile and increase target

**Comment by alex-evans123** [comment]
@minayaleon the issue is because of target defined in library and your project, edit your file and set platform version to at least 12.0 ( see example )
https://github.com/Blitz-Mobile-Apps/react-native-animated-splash/blob/master/exampleproject/ios/Podfile
